# Generated by Django 5.2.3 on 2025-06-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Articles',
        ),
    ]
